# server
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api-fake-hexagonal
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/fake_store
    username: postgres
    password: 1111

    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

