version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: fake-api-container
    restart: unless-stopped
    ports:
      - "5433:5432"   # port
    environment:
      POSTGRES_DB: fake_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
