# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1111
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fake_store_quarkus
# Hibernate
quarkus.hibernate-orm.database.generation=update
# Disable Dev Services (containers)
quarkus.oidc.devservices.enabled=false
# REST Client
org.arielzarate.infrastructure.rest.client.ApiFakeStoreClient/mp-rest/url=https://fakestoreapi.com